namespace = "cereal_pack::test"
name = "SimpleTest"

order = ['string', 'bool', 'uint8', 'dynamic_length_buffer']

[props]
    [props.string]
    type = "string"
    max_length = 8

    [props.bool]
    type = "bool"

    [props.uint8]
    type = "uint8"

    [props.int8]
    type = "int8"

    [props.uint16]
    type = "uint16"

    [props.int16]
    type = "int16"

    [props.uint32]
    type = "uint32"

    [props.int32]
    type = "int32"

    [props.uint64]
    type = "uint64"

    [props.int64]
    type = "int64"

    [props.dynamic_length_buffer]
    type = "dynamic_length_buffer"
    max_length = 32

    [props.const_length_buffer]
    type = "const_length_buffer"
    length = 16

    [props.reference]
    type = "reference"
    reference = "OneBool"

    [props.set_of_bools]
    type = "set"
    max_items = 5
    item = { type = "bool" }

    [props.set_of_references]
    type = "set"
    max_items = 5
    item = { type = "reference", reference = "OneBool" }
